import Head from 'next/head'
import { useState } from 'react'
import ActionBar from '../components/ActionBar'
// import Modal from '../components/Modal'
import Photo from '../components/Photo'
import { useModal } from '../context/ModalContext'

export default function Home() {

  const {Modal, modalState} = useModal();


  // const [modalState, setModalState] = useState(false)
  // const [modalType, setModalType] = useState('')

  return (
    <div>
      <Head>
        <title>Photo Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {modalState && <Modal/>}
        {/* {modalState && <Modal type={modalType} setModalState={setModalState} /> } */}
        {/* <ActionBar setModalState={setModalState} setModalType={setModalType} /> */}
        <ActionBar />
        <div className={`flex flex-col lg:flex-row flex-wrap justify-evenly items-center`} >
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />
          <Photo imgUrl={'/space-img.jpg'} title={"Space Image"} />

        </div>
      </main>
    </div>
  )
}
