import Head from 'next/head'
import Photo from '../components/Photo'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photo Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='flex flex-col lg:flex-row flex-wrap justify-evenly items-center mt-3'>
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />
          <Photo imgUrl={'/space-img.jpg'} />

        </div>
      </main>
    </div>
  )
}
